import type { Character } from '@/types';

export const characters: Character[] = [
  {
    id: 'bulldozer_pm',
    name: '불도저 PM',
    emoji: '🔥',
    tagline: '일단 박고 보는 행동대장',
    axes: { pace: 'impulsive', voice: 'leading', conflict: 'direct', learning: 'experimental' },
    strengths: '미친 추진력, 결단 빠름, 회의 끝내는 사람',
    weaknesses: '가끔 디테일 놓침',
    matchWith: 'careful_designer',
    tikitaka: 'impulsive_captain',
  },
  {
    id: 'impulsive_captain',
    name: '즉흥 캡틴',
    emoji: '⚡',
    tagline: '계획 없이 시작해도 어떻게든 해냄',
    axes: { pace: 'impulsive', voice: 'leading', conflict: 'direct', learning: 'systematic' },
    strengths: '빠른 판단력, 팀 분위기 업, 뭐든 일단 시작',
    weaknesses: '계획 없이 달리다 방향 잃을 때 있음',
    matchWith: 'calm_analyst',
    tikitaka: 'bulldozer_pm',
  },
  {
    id: 'mood_maker',
    name: '분위기 메이커',
    emoji: '🎤',
    tagline: '팀 에너지 충전기, 분위기 담당',
    axes: { pace: 'impulsive', voice: 'leading', conflict: 'gentle', learning: 'experimental' },
    strengths: '팀 에너지 올림, 창의적 아이디어, 소통 탁월',
    weaknesses: '기분에 따라 집중력 기복',
    matchWith: 'quiet_sniper',
    tikitaka: 'intuitive_leader',
  },
  {
    id: 'intuitive_leader',
    name: '직관 리더',
    emoji: '✨',
    tagline: '감 하나로 팀을 이끄는 타고난 리더',
    axes: { pace: 'impulsive', voice: 'leading', conflict: 'gentle', learning: 'systematic' },
    strengths: '직관적 판단, 팀원 마음 잘 읽음, 갈등 부드럽게 해결',
    weaknesses: '논리적 근거 제시가 살짝 부족할 때',
    matchWith: 'observer_planner',
    tikitaka: 'mood_maker',
  },
  {
    id: 'careful_designer',
    name: '신중한 설계자',
    emoji: '📚',
    tagline: '완벽한 계획 없이는 시작도 없어',
    axes: { pace: 'planned', voice: 'observing', conflict: 'direct', learning: 'systematic' },
    strengths: '꼼꼼한 기획, 논리적 사고, 디테일 장인',
    weaknesses: '결정이 살짝 느림',
    matchWith: 'bulldozer_pm',
    tikitaka: 'calm_analyst',
  },
  {
    id: 'quiet_sniper',
    name: '조용한 저격수',
    emoji: '🔍',
    tagline: '말은 없지만 핵심을 꿰뚫는 관찰러',
    axes: { pace: 'planned', voice: 'observing', conflict: 'direct', learning: 'experimental' },
    strengths: '예리한 분석, 타이밍 좋은 한마디, 창의적 해결책',
    weaknesses: '속 마음을 잘 안 드러냄',
    matchWith: 'mood_maker',
    tikitaka: 'observer_planner',
  },
  {
    id: 'calm_analyst',
    name: '차분한 분석가',
    emoji: '📐',
    tagline: '감정 없이 데이터로만 말하는 분석러',
    axes: { pace: 'planned', voice: 'observing', conflict: 'gentle', learning: 'systematic' },
    strengths: '논리적 사고, 체계적 접근, 갈등 중재 능력',
    weaknesses: '가끔 너무 신중해서 결정이 늦음',
    matchWith: 'impulsive_captain',
    tikitaka: 'careful_designer',
  },
  {
    id: 'observer_planner',
    name: '관찰자형 기획자',
    emoji: '🌙',
    tagline: '다 보고 있었어, 그리고 플랜도 있어',
    axes: { pace: 'planned', voice: 'observing', conflict: 'gentle', learning: 'experimental' },
    strengths: '조용한 관찰력, 창의적 기획, 갈등 없이 일 처리',
    weaknesses: '주도적으로 나서기 힘들어함',
    matchWith: 'intuitive_leader',
    tikitaka: 'quiet_sniper',
  },
  {
    id: 'dawn_inspirer',
    name: '새벽 3시 영감러',
    emoji: '🎨',
    tagline: '잠 못 자는 게 아니라 아이디어가 넘쳐서',
    axes: { pace: 'impulsive', voice: 'observing', conflict: 'gentle', learning: 'experimental' },
    strengths: '독창적인 아이디어, 예술적 감각, 부드러운 소통',
    weaknesses: '현실 감각이 살짝 부족할 때',
    matchWith: 'perfectionist_captain',
    tikitaka: 'free_supporter',
  },
  {
    id: 'free_supporter',
    name: '자유로운 서포터',
    emoji: '🌊',
    tagline: '물처럼 흘러가며 팀을 지지하는 MVP',
    axes: { pace: 'impulsive', voice: 'observing', conflict: 'gentle', learning: 'systematic' },
    strengths: '팀원 서포트 최강, 유연한 협력, 갈등 없이 조율',
    weaknesses: '자기 의견 주장이 약할 때 있음',
    matchWith: 'versatile_executor',
    tikitaka: 'dawn_inspirer',
  },
  {
    id: 'impulsive_experimenter',
    name: '즉흥 실험가',
    emoji: '🎲',
    tagline: '일단 해봐야 알지, 계획은 사치야',
    axes: { pace: 'impulsive', voice: 'observing', conflict: 'direct', learning: 'experimental' },
    strengths: '과감한 실험 정신, 빠른 피드백 루프, 솔직한 의견',
    weaknesses: '실패가 잦고 뒷정리가 서툼',
    matchWith: 'warm_leader',
    tikitaka: 'honest_ideator',
  },
  {
    id: 'honest_ideator',
    name: '솔직한 아이디어맨',
    emoji: '💡',
    tagline: '틀릴 수도 있지만 아이디어는 무한 생산',
    axes: { pace: 'impulsive', voice: 'observing', conflict: 'direct', learning: 'systematic' },
    strengths: '거침없는 아이디어, 솔직한 피드백, 즉흥적 창의성',
    weaknesses: '아이디어만 많고 실행이 약할 때 있음',
    matchWith: 'calm_pusher',
    tikitaka: 'impulsive_experimenter',
  },
  {
    id: 'perfectionist_captain',
    name: '완벽주의 캡틴',
    emoji: '🎯',
    tagline: '85점짜리 아웃풋은 내 사전에 없음',
    axes: { pace: 'planned', voice: 'leading', conflict: 'direct', learning: 'systematic' },
    strengths: '높은 퀄리티, 체계적 리더십, 논리적 방향 제시',
    weaknesses: '완벽 추구로 팀원 부담줄 때 있음',
    matchWith: 'dawn_inspirer',
    tikitaka: 'warm_leader',
  },
  {
    id: 'versatile_executor',
    name: '만능 실행가',
    emoji: '🛠️',
    tagline: '기획부터 실행까지, 못 하는 게 없음',
    axes: { pace: 'planned', voice: 'leading', conflict: 'direct', learning: 'experimental' },
    strengths: '빠른 실행력, 유연한 대응, 직설적 소통',
    weaknesses: '한 번에 너무 많이 하려다 번아웃',
    matchWith: 'free_supporter',
    tikitaka: 'calm_pusher',
  },
  {
    id: 'warm_leader',
    name: '따뜻한 리더',
    emoji: '🧭',
    tagline: '팀원 한 명 한 명을 진심으로 챙기는 리더',
    axes: { pace: 'planned', voice: 'leading', conflict: 'gentle', learning: 'systematic' },
    strengths: '팀 결속력 최강, 체계적 관리, 따뜻한 갈등 해결',
    weaknesses: '결단을 내리기까지 시간이 걸림',
    matchWith: 'impulsive_experimenter',
    tikitaka: 'perfectionist_captain',
  },
  {
    id: 'calm_pusher',
    name: '차분한 추진가',
    emoji: '🌟',
    tagline: '조용하지만 결국 목표는 달성함',
    axes: { pace: 'planned', voice: 'leading', conflict: 'gentle', learning: 'experimental' },
    strengths: '꾸준한 추진력, 창의적 접근, 부드러운 리더십',
    weaknesses: '속도가 느려 답답하게 느껴질 때 있음',
    matchWith: 'honest_ideator',
    tikitaka: 'versatile_executor',
  },
];

export function getCharacterById(id: string): Character | undefined {
  return characters.find((c) => c.id === id);
}
